[package]
name = "mcpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.1.1"
clap = {version = "4.5.4", features = ["derive"]}
dialoguer = "0.11.0"
ferinth = "2.11.0"
furse = "1.5.14"
lazy_static = "1.4.0"
reqwest = "0.12.4"
serde = "1.0.200"
thiserror = "1.0.59"
tokio = {version = "1.37.0", features = ["full"]}
toml = "0.8.12"
mrpack = { version = "0.1.0", path = "./mrpack" }